version: '3.7'
services:
  postgres:
    image: ankane/pgvector
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PW
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  admin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - PGADMIN_DEFAULT_EMAIL=${POSTGRES_USER}@domain.com
      - PGADMIN_DEFAULT_PASSWORD=$POSTGRES_PW
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - '80:80'
    volumes:
      - ./pgadmin4/pgpass:/pgadmin4/pgpass
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
    entrypoint: >
      /bin/sh -c "
      mkdir -p -m 700 /var/lib/pgadmin/storage/${POSTGRES_USER}_domain.com;
      chown -R pgadmin:pgadmin /var/lib/pgadmin/storage/${POSTGRES_USER}_domain.com;
      cp -prv /pgadmin4/pgpass /var/lib/pgadmin/storage/${POSTGRES_USER}_domain.com/;
      chmod 600 /var/lib/pgadmin/storage/${POSTGRES_USER}_domain.com/pgpass;
      /entrypoint.sh
      " 